export const styleSheetCustom = {
  container: {
    flex: 1,
    backgroundColor: "##f5fceb",
  },
  container_center: {
    marginTop: 150,
    alignItems: "center",
    padding: 1,
  },
  container_edit_bar: {
    justifyContent: "center",
    paddingTop: 40,
    paddingBottom: 5,
    paddingHorizontal: 5,
  },
  rowView: {
    flexDirection: "row",
    alignItems: "center",
    padding: 2,
    marginVertical: 10,
    marginHorizontal: 5,
  },
  rowView_close: {
    marginVertical: 1,
    padding: 1,
  },
  rowView_wrap: {
    flexWrap: "wrap",
    alignContent: "center",
    justifyContent: "center",
  },

  webview: {
    flex: 1,
  },
  textInput: {
    flex: 1,
    fontSize: 16,
    marginHorizontal: 10,
    height: 36,
    borderColor: "gray",
    borderWidth: 1,
    paddingHorizontal: 10,
  },
  text: {
    fontSize: 12,
    fontWeight: "bold",
    marginLeft: 10,
  },
  formText: {
    width: 80,
    fontSize: 16,
  },
  buttonText: {
    padding: 10,
    fontSize: 20,
    fontWeight: "bold",
    color: "white",
  },
  submitButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
    paddingHorizontal: 10,
    backgroundColor: "orange",
    borderRadius: 5,
    height: 65,
    marginVertical: 50,
  },
  submitButton_two: {
    flex: 0.4,
    height: 50,
    marginHorizontal: 1,
    marginVertical: 5,
  },
  deleteButton: {
    flex: 0.2,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
    paddingHorizontal: 10,
    backgroundColor: "red",
    borderRadius: 5,
    height: 50,
  },
  icon_image: {
    width: 36,
    height: 36,
    marginHorizontal: 18,
  },
  image: {
    width: 128,
    height: 128,
    resizeMode: "stretch",
  },
  touchableOpacityStyle: {
    position: "absolute",
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    // left: 10,
    // top: 90,
    right: 30,
    bottom: 10,
  },
  floatingButtonStyle: {
    resizeMode: "contain",
    width: 50,
    height: 50,
    backgroundColor: "black",
  },
  optionButton: {
    alignItems: "center",
    justifyContent: "center",
    width: 120,
    backgroundColor: "grey",
    padding: 10,
    marginHorizontal: 5,
    marginVertical: 2,
    borderRadius: 5,
  },
  optionButtonSelected: {
    backgroundColor: "green",
  },
  optionText: {
    color: "white",
    fontSize: 16,
  },
  selectedOptionsText: {
    marginTop: 20,
    fontSize: 16,
    fontWeight: "bold",
  },
  touchableOpacity: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 10,
    marginVertical: 5,
  },
  text_title: {
    fontWeight: "bold",
    fontSize: 20,
    marginTop: 8,
  },
  text_description: {
    fontSize: 14,
    marginTop: 8,
    color: "blue",
  },
  button: {
    alignItems: "center",
    padding: 3,
    margin: 3,
  },
  card: {
    backgroundColor: "white",
    padding: 5,
    borderRadius: 10,
    shadowColor: "black",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 5,
    margin: 20,
    width: 210,
    height: 210,
    alignContent: "center",
    justifyContent: "center",
  },
  modalView: {
    margin: 100,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    height: 500,
  },
  button_popup: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    elevation: 5,
    backgroundColor: "green",
  },
  text_popup: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
  },
};
